#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=1 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/KillBillVol.1.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/KillBillVol.1.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/KillBillVol.1 &
CUDA_VISIBLE_DEVICES=2 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/LegallyBlonde.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/LegallyBlonde.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/LegallyBlonde &
CUDA_VISIBLE_DEVICES=3 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/MidnightExpress.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/MidnightExpress.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/MidnightExpress &
CUDA_VISIBLE_DEVICES=0 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/PiratesoftheCaribbeantheCurseoftheBlackPearl.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/PiratesoftheCaribbeantheCurseoftheBlackPearl.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/PiratesoftheCaribbeantheCurseoftheBlackPearl &
wait
CUDA_VISIBLE_DEVICES=1 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/PulpFiction.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/PulpFiction.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/PulpFiction &
CUDA_VISIBLE_DEVICES=2 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/ReservoirDogs.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/ReservoirDogs.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/ReservoirDogs &
CUDA_VISIBLE_DEVICES=3 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/SavingPrivateRyan.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/SavingPrivateRyan.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/SavingPrivateRyan &
CUDA_VISIBLE_DEVICES=0 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/Terminator2.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/Terminator2.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/Terminator2 &
wait
CUDA_VISIBLE_DEVICES=1 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/TheBourneIdentity.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/TheBourneIdentity.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/TheBourneIdentity &
CUDA_VISIBLE_DEVICES=2 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/TheGodFather1.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/TheGodFather1.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/TheGodFather1 &
CUDA_VISIBLE_DEVICES=3 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/ThePianist.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/ThePianist.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/ThePianist &
CUDA_VISIBLE_DEVICES=0 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/TheSixthSense.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/TheSixthSense.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/TheSixthSense &
wait
CUDA_VISIBLE_DEVICES=1 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/TheWickerMan.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/TheWickerMan.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/TheWickerMan &
CUDA_VISIBLE_DEVICES=2 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/TheWizardofOz.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/TheWizardofOz.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/TheWizardofOz &
CUDA_VISIBLE_DEVICES=0 python /mnt/research-6f/mhasan/opensource/kinetics-i3d/extract_i3d_large_video.py --video /mnt/research-6f/mhasan/data/vsd/movies/VforVendetta.mp4 --flow /mnt/research-6f/mhasan/data/vsd/movies/VforVendetta.flow.avi --outfile /mnt/research-6f/mhasan/data/vsd/movies/VforVendetta &
wait